package wx

import (
	"context"
	"net/http"

	"chongsheng.art/wesearch/services/wxmanager/api/internal/svc"
	"github.com/zeromicro/go-zero/core/logx"
)

type MessageWithRawHTTPLogic struct {
	logx.Logger
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewMessageWithRawHTTPLogic(ctx context.Context, svcCtx *svc.ServiceContext) *MessageWithRawHTTPLogic {
	return &MessageWithRawHTTPLogic{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *MessageWithRawHTTPLogic) MessageWithRawHTTP(w http.ResponseWriter, r *http.Request) {
	// generated by custom templates
	// todo: add your logic here and delete this line

	return
}
