package wx

import (
	"context"
	"net/http"

	"chongsheng.art/wesearch/services/wxmanager/api/internal/svc"
	"github.com/zeromicro/go-zero/core/logx"
)

const (
	wxEchoKey = "echostr"
)

type WeChatValidationWithRawHTTPLogic struct {
	logx.Logger
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewWeChatValidationWithRawHTTPLogic(ctx context.Context, svcCtx *svc.ServiceContext) *WeChatValidationWithRawHTTPLogic {
	return &WeChatValidationWithRawHTTPLogic{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *WeChatValidationWithRawHTTPLogic) WeChatValidationWithRawHTTP(w http.ResponseWriter, r *http.Request) {
	// generated by custom templates
	str := r.URL.Query().Get(wxEchoKey)
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(str))
	return
}
