// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	wx "chongsheng.art/wesearch/services/wxmanager/api/internal/handler/wx"
	"chongsheng.art/wesearch/services/wxmanager/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: wx.VersionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/message",
				Handler: wx.MessageWithRawHTTPHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/message",
				Handler: wx.WeChatValidationWithRawHTTPHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/wx"),
	)
}
