// Code generated by goctl. DO NOT EDIT.
// Source: service.proto

package server

import (
	"context"

	"chongsheng.art/wesearch/services/retrieve/rpc/internal/logic"
	"chongsheng.art/wesearch/services/retrieve/rpc/internal/svc"
	"chongsheng.art/wesearch/services/retrieve/rpc/pb"
)

type RetrieveServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRetrieveServer
}

func NewRetrieveServer(svcCtx *svc.ServiceContext) *RetrieveServer {
	return &RetrieveServer{
		svcCtx: svcCtx,
	}
}

func (s *RetrieveServer) Version(ctx context.Context, in *pb.VersionReq) (*pb.VersionResp, error) {
	l := logic.NewVersionLogic(ctx, s.svcCtx)
	return l.Version(in)
}

func (s *RetrieveServer) CreateDoc(ctx context.Context, in *pb.DocumentCreateReq) (*pb.DocumentCreateResp, error) {
	l := logic.NewCreateDocLogic(ctx, s.svcCtx)
	return l.CreateDoc(in)
}

func (s *RetrieveServer) Search(ctx context.Context, in *pb.SearchReq) (*pb.SearchResp, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}
