// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.11.2
// source: rpc/userdoc.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Version
type VersionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VersionReq) Reset() {
	*x = VersionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_userdoc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionReq) ProtoMessage() {}

func (x *VersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_userdoc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionReq.ProtoReflect.Descriptor instead.
func (*VersionReq) Descriptor() ([]byte, []int) {
	return file_rpc_userdoc_proto_rawDescGZIP(), []int{0}
}

type VersionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
}

func (x *VersionResp) Reset() {
	*x = VersionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_userdoc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResp) ProtoMessage() {}

func (x *VersionResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_userdoc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResp.ProtoReflect.Descriptor instead.
func (*VersionResp) Descriptor() ([]byte, []int) {
	return file_rpc_userdoc_proto_rawDescGZIP(), []int{1}
}

func (x *VersionResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 收藏文档
type DocumentCollectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WxUID       string `protobuf:"bytes,1,opt,name=WxUID,proto3" json:"WxUID,omitempty"`             // 微信用户OpenID
	URL         string `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`                 // 文档地址
	Title       string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`             // 文档标题
	Description string `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"` // 文档描述
	Content     string `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`         // 文档内容
}

func (x *DocumentCollectReq) Reset() {
	*x = DocumentCollectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_userdoc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentCollectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentCollectReq) ProtoMessage() {}

func (x *DocumentCollectReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_userdoc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentCollectReq.ProtoReflect.Descriptor instead.
func (*DocumentCollectReq) Descriptor() ([]byte, []int) {
	return file_rpc_userdoc_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentCollectReq) GetWxUID() string {
	if x != nil {
		return x.WxUID
	}
	return ""
}

func (x *DocumentCollectReq) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *DocumentCollectReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentCollectReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DocumentCollectReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DocumentCollectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DocumentCollectResp) Reset() {
	*x = DocumentCollectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_userdoc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentCollectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentCollectResp) ProtoMessage() {}

func (x *DocumentCollectResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_userdoc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentCollectResp.ProtoReflect.Descriptor instead.
func (*DocumentCollectResp) Descriptor() ([]byte, []int) {
	return file_rpc_userdoc_proto_rawDescGZIP(), []int{3}
}

// 检索文档
type DocItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocID       string               `protobuf:"bytes,1,opt,name=DocID,proto3" json:"DocID,omitempty"`
	URL         string               `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Title       string               `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Score       float32              `protobuf:"fixed32,4,opt,name=Score,proto3" json:"Score,omitempty"`
	CollectTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=CollectTime,proto3" json:"CollectTime,omitempty"`
}

func (x *DocItem) Reset() {
	*x = DocItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_userdoc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocItem) ProtoMessage() {}

func (x *DocItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_userdoc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocItem.ProtoReflect.Descriptor instead.
func (*DocItem) Descriptor() ([]byte, []int) {
	return file_rpc_userdoc_proto_rawDescGZIP(), []int{4}
}

func (x *DocItem) GetDocID() string {
	if x != nil {
		return x.DocID
	}
	return ""
}

func (x *DocItem) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *DocItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocItem) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *DocItem) GetCollectTime() *timestamp.Timestamp {
	if x != nil {
		return x.CollectTime
	}
	return nil
}

type DocumentSearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WxUID    string   `protobuf:"bytes,1,opt,name=WxUID,proto3" json:"WxUID,omitempty"`
	Keywords []string `protobuf:"bytes,2,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
}

func (x *DocumentSearchReq) Reset() {
	*x = DocumentSearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_userdoc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentSearchReq) ProtoMessage() {}

func (x *DocumentSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_userdoc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentSearchReq.ProtoReflect.Descriptor instead.
func (*DocumentSearchReq) Descriptor() ([]byte, []int) {
	return file_rpc_userdoc_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentSearchReq) GetWxUID() string {
	if x != nil {
		return x.WxUID
	}
	return ""
}

func (x *DocumentSearchReq) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type DocumentSearchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WxUID string     `protobuf:"bytes,1,opt,name=WxUID,proto3" json:"WxUID,omitempty"`
	List  []*DocItem `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *DocumentSearchResp) Reset() {
	*x = DocumentSearchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_userdoc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentSearchResp) ProtoMessage() {}

func (x *DocumentSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_userdoc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentSearchResp.ProtoReflect.Descriptor instead.
func (*DocumentSearchResp) Descriptor() ([]byte, []int) {
	return file_rpc_userdoc_proto_rawDescGZIP(), []int{6}
}

func (x *DocumentSearchResp) GetWxUID() string {
	if x != nil {
		return x.WxUID
	}
	return ""
}

func (x *DocumentSearchResp) GetList() []*DocItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 查询用户文档
type FindDocInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocID       string               `protobuf:"bytes,1,opt,name=DocID,proto3" json:"DocID,omitempty"`
	URL         string               `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Title       string               `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	CollectTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=CollectTime,proto3" json:"CollectTime,omitempty"`
}

func (x *FindDocInfo) Reset() {
	*x = FindDocInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_userdoc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindDocInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDocInfo) ProtoMessage() {}

func (x *FindDocInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_userdoc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDocInfo.ProtoReflect.Descriptor instead.
func (*FindDocInfo) Descriptor() ([]byte, []int) {
	return file_rpc_userdoc_proto_rawDescGZIP(), []int{7}
}

func (x *FindDocInfo) GetDocID() string {
	if x != nil {
		return x.DocID
	}
	return ""
}

func (x *FindDocInfo) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *FindDocInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindDocInfo) GetCollectTime() *timestamp.Timestamp {
	if x != nil {
		return x.CollectTime
	}
	return nil
}

type FindUserDocReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WxUID string `protobuf:"bytes,1,opt,name=WxUID,proto3" json:"WxUID,omitempty"`
}

func (x *FindUserDocReq) Reset() {
	*x = FindUserDocReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_userdoc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserDocReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserDocReq) ProtoMessage() {}

func (x *FindUserDocReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_userdoc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserDocReq.ProtoReflect.Descriptor instead.
func (*FindUserDocReq) Descriptor() ([]byte, []int) {
	return file_rpc_userdoc_proto_rawDescGZIP(), []int{8}
}

func (x *FindUserDocReq) GetWxUID() string {
	if x != nil {
		return x.WxUID
	}
	return ""
}

type FindUserDocResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WxUID string         `protobuf:"bytes,1,opt,name=WxUID,proto3" json:"WxUID,omitempty"`
	List  []*FindDocInfo `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *FindUserDocResp) Reset() {
	*x = FindUserDocResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_userdoc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserDocResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserDocResp) ProtoMessage() {}

func (x *FindUserDocResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_userdoc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserDocResp.ProtoReflect.Descriptor instead.
func (*FindUserDocResp) Descriptor() ([]byte, []int) {
	return file_rpc_userdoc_proto_rawDescGZIP(), []int{9}
}

func (x *FindUserDocResp) GetWxUID() string {
	if x != nil {
		return x.WxUID
	}
	return ""
}

func (x *FindUserDocResp) GetList() []*FindDocInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_rpc_userdoc_proto protoreflect.FileDescriptor

var file_rpc_userdoc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x22, 0x27, 0x0a, 0x0b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x8e, 0x01, 0x0a, 0x12, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x57, 0x78, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x57, 0x78, 0x55, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x9b, 0x01, 0x0a, 0x07, 0x44, 0x6f, 0x63, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a,
	0x05, 0x44, 0x6f, 0x63, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x44, 0x6f,
	0x63, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x45, 0x0a, 0x11, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x78, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x57, 0x78, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x4b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x55, 0x0a, 0x12, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x57, 0x78, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x57, 0x78, 0x55,
	0x49, 0x44, 0x12, 0x29, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x44, 0x6f, 0x63, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x89, 0x01,
	0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x44, 0x6f, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x44, 0x6f, 0x63, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x44, 0x6f,
	0x63, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x46, 0x69, 0x6e,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x63, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x57,
	0x78, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x57, 0x78, 0x55, 0x49,
	0x44, 0x22, 0x56, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x78, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x57, 0x78, 0x55, 0x49, 0x44, 0x12, 0x2d, 0x0a, 0x04, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x44, 0x6f, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xbc, 0x02, 0x0a, 0x0c, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x07, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x50, 0x0a, 0x09, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x12, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4e, 0x0a, 0x09,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x6f, 0x63, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4a, 0x0a, 0x0b,
	0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x44, 0x6f, 0x63, 0x12, 0x1c, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x6f, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x6f, 0x63, 0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_userdoc_proto_rawDescOnce sync.Once
	file_rpc_userdoc_proto_rawDescData = file_rpc_userdoc_proto_rawDesc
)

func file_rpc_userdoc_proto_rawDescGZIP() []byte {
	file_rpc_userdoc_proto_rawDescOnce.Do(func() {
		file_rpc_userdoc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_userdoc_proto_rawDescData)
	})
	return file_rpc_userdoc_proto_rawDescData
}

var file_rpc_userdoc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_userdoc_proto_goTypes = []interface{}{
	(*VersionReq)(nil),          // 0: userdocument.VersionReq
	(*VersionResp)(nil),         // 1: userdocument.VersionResp
	(*DocumentCollectReq)(nil),  // 2: userdocument.DocumentCollectReq
	(*DocumentCollectResp)(nil), // 3: userdocument.DocumentCollectResp
	(*DocItem)(nil),             // 4: userdocument.DocItem
	(*DocumentSearchReq)(nil),   // 5: userdocument.DocumentSearchReq
	(*DocumentSearchResp)(nil),  // 6: userdocument.DocumentSearchResp
	(*FindDocInfo)(nil),         // 7: userdocument.FindDocInfo
	(*FindUserDocReq)(nil),      // 8: userdocument.FindUserDocReq
	(*FindUserDocResp)(nil),     // 9: userdocument.FindUserDocResp
	(*timestamp.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_rpc_userdoc_proto_depIdxs = []int32{
	10, // 0: userdocument.DocItem.CollectTime:type_name -> google.protobuf.Timestamp
	4,  // 1: userdocument.DocumentSearchResp.List:type_name -> userdocument.DocItem
	10, // 2: userdocument.FindDocInfo.CollectTime:type_name -> google.protobuf.Timestamp
	7,  // 3: userdocument.FindUserDocResp.List:type_name -> userdocument.FindDocInfo
	0,  // 4: userdocument.UserDocument.Version:input_type -> userdocument.VersionReq
	2,  // 5: userdocument.UserDocument.CreateDoc:input_type -> userdocument.DocumentCollectReq
	5,  // 6: userdocument.UserDocument.SearchDoc:input_type -> userdocument.DocumentSearchReq
	8,  // 7: userdocument.UserDocument.FindUserDoc:input_type -> userdocument.FindUserDocReq
	1,  // 8: userdocument.UserDocument.Version:output_type -> userdocument.VersionResp
	3,  // 9: userdocument.UserDocument.CreateDoc:output_type -> userdocument.DocumentCollectResp
	6,  // 10: userdocument.UserDocument.SearchDoc:output_type -> userdocument.DocumentSearchResp
	9,  // 11: userdocument.UserDocument.FindUserDoc:output_type -> userdocument.FindUserDocResp
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_userdoc_proto_init() }
func file_rpc_userdoc_proto_init() {
	if File_rpc_userdoc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_userdoc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_userdoc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_userdoc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentCollectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_userdoc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentCollectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_userdoc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_userdoc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentSearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_userdoc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentSearchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_userdoc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindDocInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_userdoc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserDocReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_userdoc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindUserDocResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_userdoc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_userdoc_proto_goTypes,
		DependencyIndexes: file_rpc_userdoc_proto_depIdxs,
		MessageInfos:      file_rpc_userdoc_proto_msgTypes,
	}.Build()
	File_rpc_userdoc_proto = out.File
	file_rpc_userdoc_proto_rawDesc = nil
	file_rpc_userdoc_proto_goTypes = nil
	file_rpc_userdoc_proto_depIdxs = nil
}
