version: "3.0"
services:
  manager:
    image: "yuchsh/wesearch-manager:latest"
    networks:
      - wesearch_dmz
    container_name: manager
    ports:
      - "7001:7001"
    volumes:
      - /home/wesearch/etc:/app/etc
      - /home/wesearch/certs:/app/certs
    depends_on:
      - userdoc
      - retrieve
  userdoc:
    image: "yuchsh/wesearch-userdoc:latest"
    container_name: userdoc
    environment:
      - POD_IP=172.22.2.3 # tell ETCD my IP by go-zero, for manager access from dmz net plane.
    networks:
      wesearch_internal:
      wesearch_dmz:
        ipv4_address: 172.22.2.3
    volumes:
      - /home/wesearch/etc:/app/etc
      - /home/wesearch/certs:/app/certs
    depends_on:
      - retrieve
  retrieve:
    image: "yuchsh/wesearch-retrieve:latest"
    networks:
      - wesearch_internal
    container_name: retrieve
    volumes:
      - /home/wesearch/etc:/app/etc
      - /home/wesearch/certs:/app/certs
networks:
  wesearch_internal:
    external: true # 即声明该网络已存在
  wesearch_dmz:
    external: true
