version: "3.0"
services:
  manager:
    image: "yuchsh/wesearch-manager:latest"
    networks:
      - wesearch_external
    container_name: manager
    ports:
      - "7001:7001"
    volumes:
      - /home/wesearch/etc:/app/etc
      - /home/wesearch/certs:/app/certs
    depends_on:
      - userdoc
      - retrieve
  userdoc:
    image: "yuchsh/wesearch-userdoc:latest"
    networks:
      - wesearch_internal
    container_name: userdoc
    volumes:
      - /home/wesearch/etc:/app/etc
      - /home/wesearch/certs:/app/certs
    depends_on:
      - retrieve
  retrieve:
    image: "yuchsh/wesearch-retrieve:latest"
    networks:
      - wesearch_internal
    container_name: retrieve
    volumes:
      - /home/wesearch/etc:/app/etc
      - /home/wesearch/certs:/app/certs
    depends_on:
      - retrieve
networks:
  wesearch_internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.1.0/24
  wesearch_external:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.2.0/24
