package {{.PkgName}}
{{ $isRawHTTPHandler := false }}{{ if eq "MessageWithRawHTTPHandler" .HandlerName }}{{ $isRawHTTPHandler = true }}{{ end }}
import (
	"net/http"
	{{ if not $isRawHTTPHandler }}"github.com/zeromicro/go-zero/rest/httpx"{{ end }}

	{{.ImportPackages}}
)

{{ if $isRawHTTPHandler }}
func {{.HandlerName}}(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
	    // generated by custom templates
		l := {{.LogicName}}.New{{.LogicType}}(r.Context(), svcCtx)
		l.{{.Call}}(w, r)
	}
}
{{ else }}
func {{.HandlerName}}(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		{{if .HasRequest}}var req types.{{.RequestType}}
		if err := httpx.Parse(r, &req); err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
			return
		}

		{{end}}l := {{.LogicName}}.New{{.LogicType}}(r.Context(), svcCtx)
		{{if .HasResp}}resp, {{end}}err := l.{{.Call}}({{if .HasRequest}}&req{{end}})
		if err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
		} else {
			{{if .HasResp}}httpx.OkJsonCtx(r.Context(), w, resp){{else}}httpx.Ok(w){{end}}
		}
	}
}
{{ end }}
