package {{.pkgName}}

{{ $isRawHTTPHandler := false }}
{{ if eq "MessageWithRawHTTP" .function }}
{{ $isRawHTTPHandler = true }}
{{ end }}
import (
    {{ if $isRawHTTPHandler }}"net/http"{{ end }}
	{{.imports}}
)

type {{.logic}} struct {
	logx.Logger
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func New{{.logic}}(ctx context.Context, svcCtx *svc.ServiceContext) *{{.logic}} {
	return &{{.logic}}{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

{{ if $isRawHTTPHandler }}
func (l *{{.logic}}) {{.function}}(w http.ResponseWriter, r *http.Request) {
    // generated by custom templates
	// todo: add your logic here and delete this line

	return
}
{{ else }}
func (l *{{.logic}}) {{.function}}({{.request}}) {{.responseType}} {
	// todo: add your logic here and delete this line

	{{.returnString}}
}
{{ end }}