Name: manager
Host: 0.0.0.0
Port: 7001

WeChat:
  AppID:
  AppSecret:
  Token:
  EncodingAESKey:

UserDocRpcConf:
  Etcd:
    Hosts:
      - 1.etcd:2379
    Key: userdoc.rpc
    CertFile: certs/etcd-client.crt
    CertKeyFile: certs/etcd-client.key
    CACertFile: certs/ca.crt
    InsecureSkipVerify: false

WeSearch:
  KeyPrefix:
    UrlCollector: https://mp.weixin.qq.com/s/
    UrlQuery: 搜索