Name: userdoc.rpc
ListenOn: 0.0.0.0:7002
Etcd:
  Hosts:
    - 1.etcd:2379
  Key: userdoc.rpc
  CertFile: certs/ca.crt
  CertKeyFile: certs/etcd-client.key
  CACertFile: certs/etcd-ca.crt
  InsecureSkipVerify: false
DB:
  DataSource: root:123456@tcp(mysql:3306)/wesearch?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
Kafka:
  Brokers:
    - 1.kafka:9092
  TopicCreateDoc: create-doc
  TopicParseDoc: parse-doc
  ConsumerGroup: userdoc
RetrieveRpcConf:
  Etcd:
    Hosts:
      - 1.etcd:2379
    Key: retrieve.rpc
    CertFile: certs/ca.crt
    CertKeyFile: certs/etcd-client.key
    CACertFile: certs/etcd-ca.crt
    InsecureSkipVerify: false